# Generated by Django 4.1.7 on 2023-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_maintenance', models.DateField()),
                ('machine_name', models.CharField(max_length=50, null=True)),
                ('is_allocate_or_not', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
